# Generated by Django 4.0.3 on 2022-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingitem',
            name='highest_bid_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
