# Generated by Django 4.0.3 on 2022-03-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listingitem_highest_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingitem',
            name='highest_bid_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
