# Generated by Django 4.0.3 on 2022-03-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listingitem_highest_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingitem',
            name='in_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
